# configs/config.yaml
defaults:
  - _self_
  - data_module: cifar10
  - task: cifar10_classification
  - trainer: gpu
  - logger: mlflow          # <-- Added default group

experiment_name: "hydra_torch_runs"
seed: 42
